In [1]:
# Raj Moliya
# 24-27-34
# M.Tech Data Science
# DSTT Assignment 2

Q1
a) Create a variable named var1 that stores an array of numbers from 0 to 30,
inclusive. Print var1 and its shape. Hint : arange

In [3]:

import numpy as np
var1 = np.arange(31)
print(f'var1: {var1} \nShape: {var1.shape}')

var1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30] 
Shape: (31,)


Q1 b) Change var2 to a validly-shaped two-dimensional matrix and store it in a
new variable called var2. Print var2 and its shape. Hint: Use the reshape function

In [4]:
var2 = var1[1:].reshape(5,6)
print(f'var2: {var2} \nShape: {var2.shape}')

var2: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]] 
Shape: (5, 6)


Q1 c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
Print var3 and its shape.

In [5]:
var3 = var1[1:].reshape(2,3,5)
print(f'var3: {var3} \nShape: {var3.shape}')

var3: [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]] 
Shape: (2, 3, 5)


Q1 d) Use two-dimensional array indexing to set the first value in the second row of var2
to -1. Now look at var1 and var3. Did they change? Explain what’s
going on. (Hint: does reshape return a view or a copy?)

In [6]:
var2[1,0] = -1
print(f'After Modifying var2 we get \nvar1: {var1} \nvar3:\n{var3}')

After Modifying var2 we get 
var1: [ 0  1  2  3  4  5  6 -1  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30] 
var3:
[[[ 1  2  3  4  5]
  [ 6 -1  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


Q1 e) Another thing that comes up a lot with array shapes is thinking about how to
aggregate over specific dimensions. Figure out how the NumPy sum function
works (and the axis argument in particular) and do the following:
(i) Sum var3 over its second dimension and print the result.
(ii) Sum var3 over its third dimension and print the result.
(iii) Sum var3 over both its first and third dimensions and print the result.

In [6]:
# (i) Sum var3 over its second dimension and print the result.
sum_var3_over_second_dimension = np.sum(var3, axis=1)
print(f'Sum of var3 over its second dimension:\n{sum_var3_over_second_dimension}')

# (ii) Sum var3 over its third dimension and print the result.
sum_var3_over_third_dimension = np.sum(var3, axis=2)
print(f'Sum of var3 over its second dimension:\n{sum_var3_over_third_dimension}')

# (iii) Sum var3 over both its first and third dimensions and print the result.
sum_var3_over_first_and_third_dimension = np.sum(var3, axis=(0,2))
print(f'Sum of var3 over its second dimension:\n{sum_var3_over_first_and_third_dimension}')


Sum of var3 over its second dimension:
[[18 13 24 27 30]
 [63 66 69 72 75]]
Sum of var3 over its second dimension:
[[ 15  32  65]
 [ 90 115 140]]
Sum of var3 over its second dimension:
[105 147 205]


Q1 f) Write code to do the following:
(i) Slice out the second row of var2 and print it.
(ii) Slice out the last column of var2 using the -1 notation and print it.
(iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

In [7]:
print(var2)
# (i) Slice out the second row of var2 and print it.
print(f'Second Row of var2: {var2[1,]}')

# (ii) Slice out the last column of var2 using the -1 notation and print it.
print(f'Last Column of var2: {var2[:,-1]}')

# (iii) Slice out the top right 2 × 2 submatrix of var2 and print it.
print(f'Top Right SubMatrix of var2:\n{var2[:2, -2:]}')

[[ 1  2  3  4  5  6]
 [-1  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Second Row of var2: [-1  8  9 10 11 12]
Last Column of var2: [ 6 12 18 24 30]
Top Right SubMatrix of var2:
[[ 5  6]
 [11 12]]


Q2 a) The most basic kind of broadcast is with a scalar, in which you can perform a
binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
perform that operation with the scalar for every element of the array. To try this
out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [8]:
vector = np.arange(10) + 1
print(f'Vector: {vector}')

Vector: [ 1  2  3  4  5  6  7  8  9 10]


Q2 b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
using the vector you just created, and adding it to a reshaped version of itself.

In [9]:
A = vector.reshape(10,1) + vector
print(f'10x10 Matrix with Aij = i+j using the above Vector: \n{A}')

10x10 Matrix with Aij = i+j using the above Vector: 
[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


Q2 c) A very common use of broadcasting is to standardize data, i.e., to make it have
zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimensions.
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )

In [10]:
data = np.exp(np.random.randn(50, 5))
print(f'Random Data Set of Integers:\n{data}')

Random Data Set of Integers:
[[ 1.96094539  5.60220622  0.73901352  0.20309595  0.82663512]
 [ 1.10038503  0.6084667   0.33264494  0.25019118  1.13154328]
 [ 0.99006914  0.57640126  0.32843755  2.31113854  0.19028162]
 [ 0.40124     2.39710318  4.664274    0.62177766  1.72257568]
 [ 0.74850058  0.71492347  1.98524178  1.51331664  0.92238184]
 [ 2.83091107  0.56128935  0.75055131  1.63472088  2.03339024]
 [ 4.36829034  7.10130551 11.92011136  3.23403643  0.27863206]
 [ 0.14064704  0.84005159  2.20634411  2.01393177  0.98052947]
 [ 1.2547817   0.21441736  0.79112231  1.65819023  2.26347764]
 [ 0.89044448  1.54933273  2.00136165  1.86680922  3.00634362]
 [ 0.67585008  2.63138067  0.7992456   0.56904073  0.14039261]
 [ 1.44860888  9.90278253  0.47104095  0.43091115  0.36637685]
 [ 0.65094608  3.33200404  0.68840346  0.76045538  3.97387182]
 [ 0.37852122  2.91285454  0.4418096   0.73670305  0.09678008]
 [ 0.73694187  2.80785235  1.55319227  0.18509753  0.64417928]
 [ 0.1712018   0.49575432 

Q2 e) Now, compute the mean and standard deviation of each column. This should
result in two vectors of length 5. You’ll need to think a little bit about how to use
the axis argument to mean and std. Store these vectors into variables and print
both of them.

In [11]:
mean = np.mean(data, axis=0)
standard_deviation = np.std(data, axis=0)
print(f'Mean: {mean}\nStandard Deviation: {standard_deviation}')

Mean: [1.16074865 1.78781888 1.52151969 1.57294383 1.38579761]
Standard Deviation: [1.23804146 1.83755778 1.79721669 1.47165816 1.5211793 ]


Q2 f) Now standardize the data matrix by 1) subtracting the mean off of each column,
and 2) dividing each column by its standard deviation. Do this via broadcasting,
and store the result in a matrix called normalized. To verify that you successfully
did it, compute the mean and standard deviation of
the columns of normalized and print them out.

In [12]:
normalized = (data - mean) / standard_deviation
print(f'Normalized Matrix: \n{normalized}')

normalized_mean = np.mean(normalized, axis=0)
normalized_std = np.std(normalized, axis=0)

print(f'Mean of normalized data: {normalized_mean}')
print(f'Standard deviation of normalized data: {normalized_std}')

Normalized Matrix: 
[[ 6.46340825e-01  2.07579178e+00 -4.35398901e-01 -9.30819342e-01
  -3.67584867e-01]
 [-4.87573501e-02 -6.41804132e-01 -6.61508851e-01 -8.98817870e-01
  -1.67142906e-01]
 [-1.37862515e-01 -6.59254162e-01 -6.63849909e-01  5.01607456e-01
  -7.85913920e-01]
 [-6.13475941e-01  3.31572865e-01  1.74867856e+00 -6.46322763e-01
   2.21392751e-01]
 [-3.32984058e-01 -5.83870298e-01  2.58022358e-01 -4.05170133e-02
  -3.04642441e-01]
 [ 1.34903594e+00 -6.67478072e-01 -4.28979088e-01  4.19778507e-02
   4.25717482e-01]
 [ 2.59081928e+00  2.89160247e+00  5.78594206e+00  1.12872176e+00
  -7.27833693e-01]
 [-8.23964016e-01 -5.15775503e-01  3.81047218e-01  2.99653782e-01
  -2.66417073e-01]
 [ 7.59530678e-02 -8.56246011e-01 -4.06404739e-01  5.79254028e-02
   5.76973421e-01]
 [-2.18332083e-01 -1.29784299e-01  2.66991711e-01  1.99683182e-01
   1.06532215e+00]
 [-3.91665861e-01  4.59066809e-01 -4.01884810e-01 -6.82157803e-01
  -8.18710191e-01]
 [ 2.32512595e-01  4.41616788e+00 -5.84503106

Q3 a) A Vandermonde matrix is a matrix generated from a vector in which each column
of the matrix is an integer power starting from zero. So, if I have a column vector
[x1, x2, . . . , xN]
T
, then the associated (square) Vandermonde matrix would be

Use what you learned about broadcasting in the previous problem to write a
function that will produce a Vandermonde matrix for a vector [1, 2, . . . ,N]T
for

any N. Do it without using a loop. Here’s a stub to get you started:
def vandermonde (N):
vec = np.arange (N) +1

Use your function for N = 12, store it in variable named vander, and print the
result.

In [15]:
def Vandermonde(N):
    base = np.arange(N) + 1
    power = np.arange(N)
    base = base.reshape(N, 1)

    vander_matrix = base ** power
    return vander_matrix

vander = Vandermonde(12)
np.set_printoptions(linewidth=200)
print(f'Vandermonde Matrix: \n{vander}')

Vandermonde Matrix: 
[[           1            1            1            1            1            1            1            1            1            1            1            1]
 [           1            2            4            8           16           32           64          128          256          512         1024         2048]
 [           1            3            9           27           81          243          729         2187         6561        19683        59049       177147]
 [           1            4           16           64          256         1024         4096        16384        65536       262144      1048576      4194304]
 [           1            5           25          125          625         3125        15625        78125       390625      1953125      9765625     48828125]
 [           1            6           36          216         1296         7776        46656       279936      1679616     10077696     60466176    362797056]
 [           1           

Q3 b) Now, let’s make a pretend linear system problem with this matrix. Create a vector
of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of
vander with the vector you just created and store that in a new vector and call it b.
Print the vector b.

In [16]:
x = np.ones(12)
print(f'Vector of all ones of Length 12: {x}')

b = vander @ x # or we can also use the '.dot()' function
print(f'Matrix-Vector Multiplication result: \n{b}')

Vector of all ones of Length 12: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Matrix-Vector Multiplication result: 
[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


Q3 c) First, solve the linear system the naïve way, pretending like you don’t know x.
Import numpy.linalg, invert V and multiply it by b. Print out your result. What
should you get for your answer? If the answer is different than what you
expected, write a sentence about that difference.

In [17]:
import numpy.linalg as linalg

naïve_way = linalg.inv(vander) @ b
print(f'Doing it the naïve way we get: \n{naïve_way}')


Doing it the naïve way we get: 
[-12.26953125   5.90625     15.421875    -6.03515625   2.05859375   0.92675781   1.00244141   1.00010681   0.99997711   1.00000131   0.99999996   1.        ]


Q3 d) Now, solve the same linear system using solve. Print out the result. Does it seem
more or less in line with what you’d expect?

In [18]:

using_solve = linalg.solve(vander, b)
print(f'Using the Solve Function we get: \n{using_solve}')

Using the Solve Function we get: 
[0.98080503 1.05139768 0.94513807 1.03151945 0.98899166 1.00248816 0.99962407 1.0000384  0.99999737 1.00000012 1.         1.        ]


In [20]:
#https://github.com/RajMoliya/Raj_DSTT_24-27-34